name: Build Signed Release APK SaeShop

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    # - name: Download Android Command-line Tools
    #   run: |
    #     mkdir -p android-sdk/cmdline-tools
    #     wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
    #     unzip cmdline-tools.zip -d android-sdk/cmdline-tools
    #     mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest

    # - name: Set up Android Tools
    #   run: |
    #     export ANDROID_HOME=$PWD/android-sdk
    #     export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
    #     yes | sdkmanager --licenses
    #     sdkmanager "platform-tools" "build-tools;30.0.3" "platforms;android-30"

    - name: Build Release APK
      run: ./gradlew assembleRelease

    # - name: Decode and Verify Keystore
    #   env:
    #     KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE_FILE_BASE64 }}
    #   run: |
    #     echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > keystore.jks
    #     keytool -list -keystore keystore.jks -storepass "${{ secrets.KEYSTORE_PASSWORD }}" || exit 1
    #     keytool -list -keystore keystore.jks -storepass "${{ secrets.KEYSTORE_PASSWORD }}" -alias "${{ secrets.KEYSTORE_ALIAS }}" || exit 1

    # - name: Sign APK
    #   env:
    #     KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    #     KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
    #     KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
    #   run: |
    #     jarsigner \
    #       -verbose \
    #       -keystore keystore.jks \
    #       -storepass "$KEYSTORE_PASSWORD" \
    #       -keypass "$KEYSTORE_KEY_PASSWORD" \
    #       app/build/outputs/apk/release/app-release-unsigned.apk \
    #       "$KEYSTORE_ALIAS"

    # - name: Align APK
    #   run: |
    #     export PATH=$PWD/android-sdk/build-tools/30.0.3:$PATH
    #     zipalign -v -p 4 \
    #       app/build/outputs/apk/release/app-release-unsigned.apk \
    #       app/build/outputs/apk/release/app-release-signed-aligned.apk

    - name: Move APK to apk/ directory
      run: |
        mkdir -p apk
        mv app/build/outputs/apk/release/app-release.apk apk/

    - name: Commit APK to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add apk/
        git commit -m "Add Signed and Aligned APK [skip ci]"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
